# junk_qc/config/inference_default.yml
# Defaults for: python -m junk_qc.scripts.run_inference

root: "/mnt/deepstore/Vidur/Junk Classification/data"
checkpoint: "/mnt/deepstore/Vidur/Junk Classification/experiment_outputs/20251203_013034_simple_cnn_aug/final_simple_cnn_aug_all_data.pt"

subfolder: "unannotated"   # which subfolder under root to scan for HDF5s
device: "cuda"
batch_size: 512
